### ISSUE TITLE
Switch Plate holes are a tad too big

### ISSUE THREAD

**Issue by Aggeloz** [victorlucachi/void_ergo#12]
Im using a Prusa Mk3s+ with the prusa slicer and i discovered that the switch holes are a tad too big and the switches move way too much and dont hold on too well. What could i do to fix this issue?

**Comment by victorlucachi** [comment]
the models switch holes measure 14.2 mm (.2mm extra for tolerance, because not all printers are equally calibrated). if you have some calipers on hand you could measure the holes, determine their dimensional accuracy, and adjust the .step file accordingly. another option would be to hotglue the switches in place.

**Comment by Aggeloz** [comment]
Alright thanks, i edited the STEP files and re printing. Thank you!

**Comment by R3ISilva** [comment]
I also have find these to be true on the plate left stl file, just fliped the plate right and reprinted it for thight fit.
